/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

 
package chatapplication;

import static chatapplication.MulticastClient.name;
import static chatapplication.MulticastClient.s;
import java.net.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Pinder
 */
public  class MulticastClient extends javax.swing.JFrame {
 public static String name;
public static String message;
public static MulticastSocket socket=null;
public static InetAddress address ;  
public static DatagramSocket s=null;
/**
     * Creates new form MulticastServerThread
     */

     // Add at the top of MulticastClient.java
private Thread screenShareServerThread;
private Thread screenShareClientThread;
// Track a ScreenShareClient instance so we can stop it later (static so the lower-level Client runner can access)
public static ScreenShareClient activeScreenShareClient;
public static Thread activeScreenShareThread;

// Stop any active screen-share viewer
public static synchronized void stopActiveScreenShare() {
    try {
        if (activeScreenShareClient != null) {
            activeScreenShareClient.stopClient();
            activeScreenShareClient = null;
        }
    } catch (Exception e) {}
    try {
        if (activeScreenShareThread != null && activeScreenShareThread.isAlive()) {
            activeScreenShareThread.interrupt();
            activeScreenShareThread = null;
        }
    } catch (Exception e) {}
}

    public MulticastClient()  {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("LAN Chat - Modern Interface");
        this.setResizable(true);
        
        // Set modern look
        getContentPane().setBackground(new java.awt.Color(45, 52, 64));
    }  
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Modern UI Components
        backgroundPanel = new javax.swing.JPanel();
        chatPanel = new javax.swing.JPanel();
        onlinePanel = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        
        sendButton = new javax.swing.JButton();
        sendFileButton = new javax.swing.JButton();
        
        // NEW SCREEN SHARING BUTTONS
        startScreenShareButton = new javax.swing.JButton();
        stopScreenShareButton = new javax.swing.JButton();
        
        exitButton = new javax.swing.JButton();
        
        chatScrollPane = new javax.swing.JScrollPane();
        chatTextArea = new javax.swing.JTextArea();
        
        inputScrollPane = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        
        onlineScrollPane = new javax.swing.JScrollPane();
        onlineTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAN Chat Room");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(900, 650));

        // Background Panel
        backgroundPanel.setBackground(new java.awt.Color(45, 52, 64));
        backgroundPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Chat Panel
        chatPanel.setBackground(new java.awt.Color(59, 66, 82));
        chatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 161, 193), 2),
            "Chat Window",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", 1, 16),
            new java.awt.Color(136, 192, 208)
        ));

        // Chat Text Area
        chatTextArea.setEditable(false);
        chatTextArea.setBackground(new java.awt.Color(236, 239, 244));
        chatTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14));
        chatTextArea.setForeground(new java.awt.Color(46, 52, 64));
        chatTextArea.setLineWrap(true);
        chatTextArea.setWrapStyleWord(true);
        chatTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        chatScrollPane.setViewportView(chatTextArea);
        chatScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // Online Panel
        onlinePanel.setBackground(new java.awt.Color(59, 66, 82));
        onlinePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 161, 193), 2),
            "Online Users",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", 1, 16),
            new java.awt.Color(136, 192, 208)
        ));

        // Online Users Text Area
        onlineTextArea.setEditable(false);
        onlineTextArea.setBackground(new java.awt.Color(236, 239, 244));
        onlineTextArea.setFont(new java.awt.Font("Segoe UI", 0, 13));
        onlineTextArea.setForeground(new java.awt.Color(46, 52, 64));
        onlineTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        onlineScrollPane.setViewportView(onlineTextArea);
        onlineScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // Input Panel
        inputPanel.setBackground(new java.awt.Color(59, 66, 82));
        inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 161, 193), 2),
            "Type your message",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", 1, 14),
            new java.awt.Color(136, 192, 208)
        ));

        // Input Text Area
        inputTextArea.setBackground(new java.awt.Color(236, 239, 244));
        inputTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14));
        inputTextArea.setForeground(new java.awt.Color(46, 52, 64));
        inputTextArea.setLineWrap(true);
        inputTextArea.setWrapStyleWord(true);
        inputTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        inputScrollPane.setViewportView(inputTextArea);
        inputScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // Send Button
        sendButton.setBackground(new java.awt.Color(163, 190, 140));
        sendButton.setFont(new java.awt.Font("Segoe UI", 1, 14));
        sendButton.setForeground(new java.awt.Color(46, 52, 64));
        sendButton.setText("Send");
        sendButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 16, 8, 16));
        sendButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendButton.setFocusPainted(false);
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendButton.setBackground(new java.awt.Color(143, 188, 187));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendButton.setBackground(new java.awt.Color(163, 190, 140));
            }
        });
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        // Send File Button
        sendFileButton.setBackground(new java.awt.Color(94, 129, 172));
        sendFileButton.setFont(new java.awt.Font("Segoe UI", 1, 14));
        sendFileButton.setForeground(new java.awt.Color(236, 239, 244));
        sendFileButton.setText("Send File");
        sendFileButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 16, 8, 16));
        sendFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendFileButton.setFocusPainted(false);
        sendFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendFileButton.setBackground(new java.awt.Color(129, 161, 193));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendFileButton.setBackground(new java.awt.Color(94, 129, 172));
            }
        });
        sendFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileButtonActionPerformed(evt);
            }
        });

        // START SCREEN SHARE BUTTON
        startScreenShareButton.setBackground(new java.awt.Color(180, 142, 173));
        startScreenShareButton.setFont(new java.awt.Font("Segoe UI", 1, 14));
        startScreenShareButton.setForeground(new java.awt.Color(46, 52, 64));
        startScreenShareButton.setText("Start Screen Share");
        startScreenShareButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 16, 8, 16));
        startScreenShareButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startScreenShareButton.setFocusPainted(false);
        startScreenShareButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startScreenShareButton.setBackground(new java.awt.Color(163, 120, 155));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startScreenShareButton.setBackground(new java.awt.Color(180, 142, 173));
            }
        });
        startScreenShareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startScreenShareButtonActionPerformed(evt);
            }
        });

        // STOP SCREEN SHARE BUTTON
        stopScreenShareButton.setBackground(new java.awt.Color(208, 135, 112));
        stopScreenShareButton.setFont(new java.awt.Font("Segoe UI", 1, 14));
        stopScreenShareButton.setForeground(new java.awt.Color(46, 52, 64));
        stopScreenShareButton.setText("Stop Screen Share");
        stopScreenShareButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 16, 8, 16));
        stopScreenShareButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stopScreenShareButton.setFocusPainted(false);
        stopScreenShareButton.setEnabled(false); // Initially disabled
        stopScreenShareButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (stopScreenShareButton.isEnabled()) {
                    stopScreenShareButton.setBackground(new java.awt.Color(191, 97, 106));
                }
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                if (stopScreenShareButton.isEnabled()) {
                    stopScreenShareButton.setBackground(new java.awt.Color(208, 135, 112));
                }
            }
        });
        stopScreenShareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopScreenShareButtonActionPerformed(evt);
            }
        });

        // Exit Button
        exitButton.setBackground(new java.awt.Color(191, 97, 106));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14));
        exitButton.setForeground(new java.awt.Color(236, 239, 244));
        exitButton.setText("Exit Chat");
        exitButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 16, 8, 16));
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.setFocusPainted(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButton.setBackground(new java.awt.Color(208, 112, 121));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButton.setBackground(new java.awt.Color(191, 97, 106));
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        // Layout for chat panel
        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        // Layout for online panel
        javax.swing.GroupLayout onlinePanelLayout = new javax.swing.GroupLayout(onlinePanel);
        onlinePanel.setLayout(onlinePanelLayout);
        onlinePanelLayout.setHorizontalGroup(
            onlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(onlineScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        onlinePanelLayout.setVerticalGroup(
            onlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(onlineScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        // Layout for input panel - UPDATED TO INCLUDE NEW BUTTONS
        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addComponent(inputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(startScreenShareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopScreenShareButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startScreenShareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopScreenShareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        // Main layout
        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(chatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(onlinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onlinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        String x="***** "+name+" has logged out from the chat room *****";
        
        byte buf[]=x.getBytes();
        try{  
            InetAddress group = InetAddress.getByName("230.0.0.1");
            DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
            s.send(packet);
        }catch(Exception e){}
        
        x="exited";
        buf=x.getBytes();
        try{
            InetAddress group=InetAddress.getByName("230.0.0.2");
            DatagramPacket packet=new DatagramPacket(buf, buf.length,group,5000);
            s.send(packet);
            
            socket.leaveGroup(address);
            s.close();
        }
        catch(Exception e){}
        
        this.setVisible(false);
        new ChatApp().setVisible(true);   
    }//GEN-LAST:event_exitButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String text= inputTextArea.getText();
        if(!text.equals(""))
        {    
            message=name+": "+text;
            
            try {
                byte[] buf = message.getBytes();
                InetAddress group = InetAddress.getByName("230.0.0.1");
                DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
                s.send(packet);  
            }       
            catch (IOException e) {
                MulticastClient.socket.close();
            }   
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    // NEW SCREEN SHARING ACTION METHODS
private void startScreenShareButtonActionPerformed(java.awt.event.ActionEvent evt) { 
    startScreenShareButton.setEnabled(false);
    stopScreenShareButton.setEnabled(true);

    try {
        String ip = InetAddress.getLocalHost().getHostAddress();   // get this machine's IP
        String screenShareMsg = "***** " + name + " started screen sharing at " + ip + ":5555 *****";

        byte[] buf = screenShareMsg.getBytes();
        InetAddress group = InetAddress.getByName("230.0.0.1");
        DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
        s.send(packet);
    } catch (Exception e) {
        chatTextArea.append("[Screen share notification error: " + e.getMessage() + "]\n");
    }

    // ✅ Start Screen Share Server
    try {
        screenShareServerThread = new Thread(new ScreenShareServer(5555));
        screenShareServerThread.start();
        chatTextArea.append("[Screen sharing started on port 5555]\n");
    } catch (Exception e) {
        chatTextArea.append("[Error starting screen share: " + e.getMessage() + "]\n");
    }
}



private void stopScreenShareButtonActionPerformed(java.awt.event.ActionEvent evt) { 
    startScreenShareButton.setEnabled(true);
    stopScreenShareButton.setEnabled(false);

    String screenShareMsg = "***** " + name + " stopped screen sharing *****";
    try {
        byte[] buf = screenShareMsg.getBytes();
        InetAddress group = InetAddress.getByName("230.0.0.1");
        DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
        s.send(packet);
    } catch (Exception e) {
        chatTextArea.append("[Screen share notification error: " + e.getMessage() + "]\n");
    }

    // ✅ Stop server
    try {
        if (screenShareServerThread != null && screenShareServerThread.isAlive()) {
            screenShareServerThread.interrupt();
            screenShareServerThread = null;
        }
        chatTextArea.append("[Screen sharing stopped]\n");
    } catch (Exception e) {
        chatTextArea.append("[Error stopping screen share: " + e.getMessage() + "]\n");
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                    new MulticastClient().setVisible(true);
                
                    }
               }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JScrollPane chatScrollPane;
    public static javax.swing.JTextArea chatTextArea;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JScrollPane inputScrollPane;
    public static javax.swing.JTextArea inputTextArea;
    private javax.swing.JPanel onlinePanel;
    private javax.swing.JScrollPane onlineScrollPane;
    public static javax.swing.JTextArea onlineTextArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton sendFileButton;
    
    // NEW SCREEN SHARING BUTTON DECLARATIONS
    private javax.swing.JButton startScreenShareButton;
    private javax.swing.JButton stopScreenShareButton;
    
    // End of variables declaration//GEN-END:variables
    
    private void sendFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            try {
                // Start a server socket to send the file
                java.net.ServerSocket fileServer = new java.net.ServerSocket(0); // random free port
                int port = fileServer.getLocalPort();
                String localIP = java.net.InetAddress.getLocalHost().getHostAddress();
                String fileMsg = "[FILE]" + file.getName() + "|" + file.length() + "|" + localIP + "|" + port;
                // Multicast file info
                byte[] buf = (name + ": " + fileMsg).getBytes();
                InetAddress group = InetAddress.getByName("230.0.0.1");
                DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
                s.send(packet);
                chatTextArea.append("[File sharing started: " + file.getName() + "]\n");
                // Start a thread to send the file
                new Thread(() -> {
                    try (java.net.Socket client = fileServer.accept();
                         java.io.FileInputStream fis = new java.io.FileInputStream(file);
                         java.io.OutputStream os = client.getOutputStream()) {
                        byte[] buffer = new byte[4096];
                        int read;
                        while ((read = fis.read(buffer)) != -1) {
                            os.write(buffer, 0, read);
                        }
                        os.flush();
                        chatTextArea.append("[File sent: " + file.getName() + "]\n");
                    } catch (Exception ex) {
                        chatTextArea.append("[File send failed: " + ex.getMessage() + "]\n");
                    } finally {
                        try { fileServer.close(); } catch (Exception ex) {}
                    }
                }).start();
            } catch (Exception ex) {
                chatTextArea.append("[File sharing error: " + ex.getMessage() + "]\n");
            }
        }
    }
}

 

 class Client implements Runnable {
  
     Client(){
         try{
         MulticastClient.socket = new MulticastSocket(4446) ;
        MulticastClient. s=new DatagramSocket();
        
        MulticastClient. address=InetAddress.getByName("230.0.0.1");
      MulticastClient.socket.joinGroup(MulticastClient.address);
      }
        catch(Exception e)
        {JOptionPane.showMessageDialog(new ChatApp(), "Sorry,Cannot bind");}}
  @Override
  public void run(){
      Thread t3=new Thread(new OnlineStatus());
         
           t3.start();
       Thread t4=new Thread(new ReceiveOnlineStatus());
            t4.start();
       newUser();
           
     
           
  
      
  while(true)
      {  
          
      try{
    
      
         
     
         DatagramPacket packet;
       
         
         
         byte[] buf = new byte[256];
         packet = new DatagramPacket(buf, buf.length);
         
         MulticastClient.socket.receive(packet);
        
         String received = new String(packet.getData(), 0, packet.getLength());
        
                // Handle screen share start/stop notifications
                try {
                    if (received.contains("started screen sharing at")) {
                        // Message format: ***** name started screen sharing at 172.20.10.7:5555 *****
                        String lower = received;
                        // avoid starting viewer for our own announcement
                        if (lower.contains("***** " + name + " started screen sharing")) {
                            // ignore our own start message
                        } else {
                            int atIdx = lower.indexOf("started screen sharing at");
                            if (atIdx >= 0) {
                                // extract ip:port by finding the substring between 'at ' and ' *****'
                                int atPos = lower.indexOf("at ");
                                int endPos = lower.indexOf(" *****", atPos);
                                if (atPos >= 0 && endPos > atPos) {
                                    String ipPort = lower.substring(atPos + 3, endPos).trim();
                                    String[] partsIp = ipPort.split(":");
                                    if (partsIp.length == 2) {
                                        String ip = partsIp[0];
                                        int port = Integer.parseInt(partsIp[1]);
                                        // start viewer in new thread
                                        try {
                                            MulticastClient.stopActiveScreenShare();
                                            MulticastClient.activeScreenShareClient = new ScreenShareClient(ip, port);
                                            MulticastClient.activeScreenShareThread = new Thread(MulticastClient.activeScreenShareClient);
                                            MulticastClient.activeScreenShareThread.start();
                                            MulticastClient.chatTextArea.append("[Connecting to screen share " + ip + ":" + port + "]\n");
                                        } catch (Exception ex) {
                                            MulticastClient.chatTextArea.append("[Screen viewer error: " + ex.getMessage() + "]\n");
                                        }
                                    }
                                }
                            }
                        }
                    } else if (received.contains("stopped screen sharing")) {
                        // If someone stopped, stop the active viewer (if any)
                        // avoid stopping if the stop is for someone else, but for simplicity stop viewer when stop message arrives
                        MulticastClient.stopActiveScreenShare();
                        MulticastClient.chatTextArea.append("[Screen sharing stopped]\n");
                    }
                } catch (Exception ex) {
                    MulticastClient.chatTextArea.append("[Screen share message parse error: " + ex.getMessage() + "]\n");
                }

                if (received.contains("[FILE]")) {
             // Format: [FILE]filename|filesize|ip|port
             try {
                 String[] parts = received.split("\\[FILE\\]");
                 String senderMsg = parts[0];
                 String fileInfo = parts[1];
                 String[] fileParts = fileInfo.split("\\|");
                 String fileName = fileParts[0];
                 String fileSize = fileParts[1];
                 String fileIP = fileParts[2];
                 int filePort = Integer.parseInt(fileParts[3]);
                 MulticastClient.chatTextArea.append(senderMsg + "[File: " + fileName + "]\n");
                 // Show a dialog to download
                 int resp = javax.swing.JOptionPane.showConfirmDialog(null, senderMsg + " sent file '" + fileName + "' (" + fileSize + " bytes). Download?", "File Received", javax.swing.JOptionPane.YES_NO_OPTION);
                 if (resp == javax.swing.JOptionPane.YES_OPTION) {
                     javax.swing.JFileChooser saveChooser = new javax.swing.JFileChooser();
                     saveChooser.setSelectedFile(new java.io.File(fileName));
                     int saveResult = saveChooser.showSaveDialog(null);
                     if (saveResult == javax.swing.JFileChooser.APPROVE_OPTION) {
                         java.io.File saveFile = saveChooser.getSelectedFile();
                         try (java.net.Socket sock = new java.net.Socket(fileIP, filePort);
                              java.io.FileOutputStream fos = new java.io.FileOutputStream(saveFile);
                              java.io.InputStream is = sock.getInputStream()) {
                             byte[] buffer = new byte[4096];
                             int read;
                             long total = 0;
                             while ((read = is.read(buffer)) != -1) {
                                 fos.write(buffer, 0, read);
                                 total += read;
                                 if (total >= Long.parseLong(fileSize)) break;
                             }
                             fos.flush();
                             MulticastClient.chatTextArea.append("[File downloaded: " + saveFile.getAbsolutePath() + "]\n");
                         } catch (Exception ex) {
                             MulticastClient.chatTextArea.append("[File download failed: " + ex.getMessage() + "]\n");
                         }
                     }
                 }
             } catch (Exception ex) {
                 MulticastClient.chatTextArea.append("[File receive error: " + ex.getMessage() + "]\n");
             }
         } else {
             MulticastClient.chatTextArea.setText(MulticastClient.chatTextArea.getText()+received+"\n");
         }
         MulticastClient.inputTextArea.setText("");
                  }catch(IOException e){System.err.println(e);}
       }  
 
 
 } void newUser(){String x="***** "+name+" has logged into the chat room *****";
            byte buf[]=x.getBytes();
              try{  InetAddress group = InetAddress.getByName("230.0.0.1");
                DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
              
             
               s.send(packet);
              }catch(Exception e){}}
  }
 
 
  








   
               







